source:
  type: csv   # options: csv, jira
  scoring_issues_csv: /Users/swatisingh/Documents/Rohit/GIT/AgenticJIraAssignment/src/data/scoring_issues.csv
  training_issues_csv: /Users/swatisingh/Documents/Rohit/GIT/AgenticJIraAssignment/src/data/training_issues.csv
  jql: "project = PROJ AND status = \"To Do\""

jira:
  base_url: https://your-domain.atlassian.net
  email: your-email@example.com
  api_token: your-api-token
  project_key: PROJ

TrainingModel: True
ScoringModel: False
LoadTeamMembers: true